# Source: vllm-stack/templates/poddisruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "pd-pdb"
  namespace: test-ns
spec:
  maxUnavailable: 1
---
# Source: vllm-stack/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "pd-router-service-account"
  namespace: test-ns
---
# Source: vllm-stack/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pd-llama-prefill-storage-claim"
  namespace: test-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Default to 20Gi if not set
---
# Source: vllm-stack/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pd-llama-decode-storage-claim"
  namespace: test-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Default to 20Gi if not set
---
# Source: vllm-stack/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "pd-pod-reader"
  namespace: test-ns
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "patch"]
---
# Source: vllm-stack/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pd-deployment-access-binding
  namespace: test-ns
subjects:
  - kind: ServiceAccount
    name: pd-router-service-account
    namespace: test-ns
roleRef:
  kind: Role
  name: pd-pod-reader
  apiGroup: rbac.authorization.k8s.io
---
# Source: vllm-stack/templates/service-router.yaml
apiVersion: v1
kind: Service
metadata:
  name: "pd-router-service"
  namespace: test-ns
  labels:
    environment: router
    release: router
spec:
  type: ClusterIP
  ports:
    - name: "router-port"
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: "lmcache-port"
      port: 9000
      targetPort: lmcache-port
      protocol: TCP
    
  selector:
    environment: router
    release: router
---
# Source: vllm-stack/templates/service-vllm.yaml
apiVersion: v1
kind: Service
metadata:
  name: "pd-llama-prefill-engine-service"
  namespace: test-ns
  labels:
    environment: test
    release: test
spec:
  type: ClusterIP
  ports:
    - name: "service-port"
      port: 80
      targetPort: "container-port"
      protocol: TCP
    - name: zmq-port
      port: 55555
      targetPort: zmq-port
      protocol: TCP
    - name: ucx-port
      port: 9999
      targetPort: ucx-port
      protocol: TCP
    
  selector:
    model: "llama-prefill"
    helm-release-name: "pd"
---
# Source: vllm-stack/templates/service-vllm.yaml
apiVersion: v1
kind: Service
metadata:
  name: "pd-llama-decode-engine-service"
  namespace: test-ns
  labels:
    environment: test
    release: test
spec:
  type: ClusterIP
  ports:
    - name: "service-port"
      port: 80
      targetPort: "container-port"
      protocol: TCP
    - name: zmq-port
      port: 55555
      targetPort: zmq-port
      protocol: TCP
    - name: ucx-port
      port: 9999
      targetPort: ucx-port
      protocol: TCP
    
  selector:
    model: "llama-decode"
    helm-release-name: "pd"
---
# Source: vllm-stack/templates/deployment-router.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pd-deployment-router"
  namespace: test-ns
  labels:
    environment: router
    release: router
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      environment: router
      release: router
  template:
    metadata:
      labels:
        environment: router
        release: router
    spec:
      serviceAccountName: pd-router-service-account
      containers:
      - name: router-container
        image: "lmcache/lmstack-router:pd"
        imagePullPolicy: "Always"
        env:
          - name: LMCACHE_LOG_LEVEL
            value: "DEBUG"
        args:
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8000"
          - "--service-discovery"
          - "k8s"
          - "--k8s-namespace"
          - "default"
          - "--k8s-service-discovery-type"
          - "pod-ip"
          - "--k8s-label-selector"
          - environment=test,release=test
          - "--routing-logic"
          - "disaggregated_prefill"
          - "--engine-stats-interval"
          - "15"
          - "--request-stats-window"
          - "60"
          - --prefill-model-labels
          - llama-prefill
          - --decode-model-labels
          - llama-decode
        resources:
          requests:
            cpu: "4"
            memory: "16G"
          limits:
            cpu: "4"
            memory: "32G"
        ports:
          - name: "router-cport"
            containerPort: 8000
          - name: "lmcache-port"
            containerPort: 9000
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
        startupProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
---
# Source: vllm-stack/templates/deployment-vllm-multi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pd-llama-prefill-deployment-vllm"
  namespace: test-ns
  labels:
    model: llama-prefill
    helm-release-name: pd
    environment: test
    release: test
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      model: llama-prefill
      helm-release-name: pd
      environment: test
      release: test
  progressDeadlineSeconds: 1200
  template:
    metadata:
      labels:
        model: llama-prefill
        helm-release-name: pd
        environment: test
        release: test
    spec:
      hostIPC: true
      hostPID: true
      hostname: "pd-llama-prefill-vllm-stack"
      subdomain: "pd-llama-prefill-engine-service"
      containers:
        - name: "vllm"
          image: "vllm/vllm-openai:latest"
          securityContext:
            runAsNonRoot: false
          command:
          - "/opt/venv/bin/vllm"
          - "serve"
          - "meta-llama/Meta-Llama-3-8B"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8000"
          - "--enable-prefix-caching"
          - "--max-model-len"
          - "32000"
          - "--gpu_memory_utilization"
          - "0.6"
          - "--kv-transfer-config"
          - '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_producer","kv_connector_extra_config":{"discard_partial_chunks": false, "lmcache_rpc_port": "sender"}}'
          imagePullPolicy: "Always"
          env:
          - name: HF_HOME
            value: /data
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: LMCACHE_LOG_LEVEL
            value: "DEBUG"
          - name: PROMETHEUS_MULTIPROC_DIR
            value: "/tmp"
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                key: hf_api_token
                name: hf-secret
          - name: LMCACHE_USE_EXPERIMENTAL
            value: "True"
          - name: VLLM_RPC_TIMEOUT
            value: "1000000"
          - name: CUDA_VISIBLE_DEVICES
            value: "0"
          - name: LMCACHE_LOCAL_CPU
            value: "False"
          - name: LMCACHE_MAX_LOCAL_CPU_SIZE
            value: "0"
          - name: LMCACHE_REMOTE_SERDE
            value: "NULL"
          - name: UCX_TLS
            value: "cuda_ipc,cuda_copy,tcp"
          - name: LMCACHE_ENABLE_NIXL
            value: "True"
          - name: LMCACHE_NIXL_ROLE
            value: "sender"
          - name: LMCACHE_NIXL_RECEIVER_HOST
            # value:  "0.0.0.0"
            value: "vllm-llama-decode-engine-service"
          - name: LMCACHE_NIXL_RECEIVER_PORT
            value: "55555"
          - name: LMCACHE_NIXL_BUFFER_SIZE
            value: "1073741824"
          - name: LMCACHE_NIXL_BUFFER_DEVICE
            value: "cuda"
          - name: LMCACHE_NIXL_ENABLE_GC
            value: "True"
          - name: PATH
            value: "/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          - name: LD_LIBRARY_PATH
            value: "/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
          ports:
            - name: "container-port"
              containerPort: 8000
            - name: zmq-port
              containerPort: 55555
            - name: ucx-port
              containerPort: 9999          
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
          volumeMounts:
          - name: pd-storage
            mountPath: /data
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      volumes:
        - name: pd-storage
          persistentVolumeClaim:
            claimName: "pd-llama-prefill-storage-claim"
---
# Source: vllm-stack/templates/deployment-vllm-multi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pd-llama-decode-deployment-vllm"
  namespace: test-ns
  labels:
    model: llama-decode
    helm-release-name: pd
    environment: test
    release: test
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      model: llama-decode
      helm-release-name: pd
      environment: test
      release: test
  progressDeadlineSeconds: 1200
  template:
    metadata:
      labels:
        model: llama-decode
        helm-release-name: pd
        environment: test
        release: test
    spec:
      hostIPC: true
      hostPID: true
      hostname: "pd-llama-decode-vllm-stack"
      subdomain: "pd-llama-decode-engine-service"
      containers:
        - name: "vllm"
          image: "vllm/vllm-openai:latest"
          securityContext:
            runAsNonRoot: false
          command:
          - "/opt/venv/bin/vllm"
          - "serve"
          - "meta-llama/Meta-Llama-3-8B"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8000"
          - "--enable-prefix-caching"
          - "--max-model-len"
          - "32000"
          - "--kv-transfer-config"
          - '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_consumer","kv_connector_extra_config":{"discard_partial_chunks": false, "lmcache_rpc_port": "receiver"}}'
          imagePullPolicy: "Always"
          env:
          - name: HF_HOME
            value: /data
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: LMCACHE_LOG_LEVEL
            value: "DEBUG"
          - name: PROMETHEUS_MULTIPROC_DIR
            value: "/tmp"
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                key: hf_api_token
                name: hf-secret
          - name: LMCACHE_USE_EXPERIMENTAL
            value: "True"
          - name: VLLM_RPC_TIMEOUT
            value: "1000000"
          - name: CUDA_VISIBLE_DEVICES
            value: "1"
          - name: LMCACHE_LOCAL_CPU
            value: "False"
          - name: LMCACHE_MAX_LOCAL_CPU_SIZE
            value: "0"
          - name: LMCACHE_REMOTE_SERDE
            value: "NULL"
          - name: UCX_TLS
            value: "cuda_ipc,cuda_copy,tcp"
          - name: LMCACHE_ENABLE_NIXL
            value: "True"
          - name: LMCACHE_NIXL_ROLE
            value: "receiver"
          - name: LMCACHE_NIXL_RECEIVER_HOST
            value: "0.0.0.0"
          - name: LMCACHE_NIXL_RECEIVER_PORT
            value: "55555"
          - name: LMCACHE_NIXL_BUFFER_SIZE
            value: "1073741824"
          - name: LMCACHE_NIXL_BUFFER_DEVICE
            value: "cuda"
          - name: LMCACHE_NIXL_ENABLE_GC
            value: "True"
          - name: PATH
            value: "/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          - name: LD_LIBRARY_PATH
            value: "/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
          ports:
            - name: "container-port"
              containerPort: 8000
            - name: zmq-port
              containerPort: 55555
            - name: ucx-port
              containerPort: 9999          
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
          volumeMounts:
          - name: pd-storage
            mountPath: /data
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      volumes:
        - name: pd-storage
          persistentVolumeClaim:
            claimName: "pd-llama-decode-storage-claim"