load:
  interval: 10
  sweep:
    num_stages: 10
    stage_duration: 300
    type: linear
  type: constant
api: 
  type: completion
  streaming: true
server:
  type: vllm
  model_name: HuggingFaceTB/SmolLM2-135M-Instruct
  base_url: http://0.0.0.0:8000
  ignore_eos: true
tokenizer:
  pretrained_model_name_or_path: HuggingFaceTB/SmolLM2-135M-Instruct
data:
  shared_prefix:
    num_groups: 1
    num_prompts_per_group: 100000
    output_len: 128
    question_len: 64
    system_prompt_len: 64
  type: shared_prefix
metrics:
  type: prometheus
  prometheus:
    url: http://localhost:9090
    scrape_interval: 15
report:
  request_lifecycle:
    summary: true
    per_stage: true
    per_request: false
  prometheus:
    summary: true
    per_stage: false
